services:
  db:
    image: mariadb:latest
    container_name: ecomm-mariadb
    restart: unless-stopped
    ports:
      - "3306:3306"
    environment:
      MYSQL_ROOT_PASSWORD: rootpassword
    volumes:
      - ecomm_mariadb_data:/var/lib/mysql
      - ./conf/init.sql:/docker-entrypoint-initdb.d/init.sql

  authapi:
    build:
      context: AuthAPI
      dockerfile: Dockerfile
    ports:
      - 8080:8080
    env_file:
      - conf/auth.env
    depends_on:
      - db
      
  ecommapi:
    build:
      context: EcommAPI
      dockerfile: Dockerfile
    ports:
      - 8081:8080
    env_file:
      - conf/ecomm.env
    depends_on:
      - db

volumes:
  ecomm_mariadb_data: