services:
  db:
    image: mariadb:latest
    container_name: ecomm-mariadb
    restart: unless-stopped
    ports:
      - "3306:3306"
    environment:
      MYSQL_ROOT_PASSWORD: rootpassword
    volumes:
      - ecomm_mariadb_data:/var/lib/mysql
      - ./conf/init.sql:/docker-entrypoint-initdb.d/init.sql
  authapi:
    build:
      context: AuthAPI
      dockerfile: Dockerfile
    ports:
      - 8080:8080
    env_file:
      - conf/auth.env
  ecommapi:
    build:
      context: EcommAPI
      dockerfile: Dockerfile
    ports:
      - 8081:8080
    env_file:
      - conf/ecomm.env
  mobile-app:
    build:
      context: ecomm-mobile-app
      dockerfile: Dockerfile
    container_name: ecomm-mobile-app
    stdin_open: true
    tty: true
    volumes:
      - ./ecomm-mobile-app:/app
      - /app/node_modules
    depends_on:
      - authapi
      - ecommapi


volumes:
  ecomm_mariadb_data: