spring:
  application:
    name: EcommAPI
  datasource:
    url: ${DB_URI:jdbc:mariadb://localhost:3306/ecomm}
    username: ${DB_USER:root}
    password: ${DB_PASS:rootpassword}
    driverClassName: org.mariadb.jdbc.Driver
  sql:
    init:
      mode: always
      data-locations: classpath:data.sql
  cloud:
    compatibility-verifier:
      enabled: false
auth:
  api:
    url: ${AUTH_API_URL:http://localhost:8080/api/v1}