spring:
  application:
    name: EcommAPI
  datasource:
    url: jdbc:h2:mem:ecommdb;mode=oracle
    username: ecomm
    password: mmoce # Note: This password is not used yet and will never be use on production env, this is not git credential leak
    driverClassName: org.h2.Driver
  jpa:
    database-platform: org.hibernate.dialect.H2Dialect
  h2:
    console:
      enabled: true
      settings:
        web-allow-others: true
  cloud:
    compatibility-verifier:
      enabled: false
auth:
  api:
    url: ${AUTH_API_URL:http://localhost:8080/api/v1}