spring:
  application:
    name: AuthApi
  datasource:
    url: ${DB_URI:jdbc:mariadb://localhost:3306/auth}
    username: ${DB_USER:root}
    password: ${DB_PASS:rootpassword}
    driverClassName: org.mariadb.jdbc.Driver
  sql:
    init:
      mode: always
      data-locations: classpath:data.sql
  cloud:
    compatibility-verifier:
      enabled: false