spring:
  application:
    name: AuthApi
  datasource:
    url: jdbc:mariadb://localhost:3306/auth
    username: root
    password: rootpassword
    driverClassName: org.mariadb.jdbc.Driver
  sql:
    init:
      mode: always
      data-locations: classpath:data.sql
  cloud:
    compatibility-verifier:
      enabled: false